
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin3
 */
public class ConverterWindow extends javax.swing.JFrame {

    private String currencies[];
    private String countries[];
    private Double fromAmount;
    
    
    /**
     * Creates new form ConverterWindow
     */
    public ConverterWindow() {
        JsonReader jsonReader = new JsonReader("currencylist.json");
        currencies = jsonReader.getUnits();
        countries = jsonReader.getCountries();
        
        //currencies = new String[] {"JPY","USD","PES"};
        initComponents();
        
        //setFromNumberFormat("USD");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromCurrencyList = new javax.swing.JComboBox();
        toCurrencyList = new javax.swing.JComboBox();
        exchangeRate = new javax.swing.JTextField();
        rateLabel = new javax.swing.JLabel();
        amountNameLabel = new javax.swing.JLabel();
        convertedAmountNameLabel = new javax.swing.JLabel();
        enterAmountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JFormattedTextField();
        convertedAmount = new javax.swing.JFormattedTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        updateMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter");
        setName("Currency Converter"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        fromCurrencyList.setModel(new javax.swing.DefaultComboBoxModel(currencies));
        fromCurrencyList.setToolTipText("");
        fromCurrencyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCurrencyListActionPerformed(evt);
            }
        });

        toCurrencyList.setModel(new javax.swing.DefaultComboBoxModel(currencies));
        toCurrencyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCurrencyListActionPerformed(evt);
            }
        });

        exchangeRate.setEditable(false);
        exchangeRate.setFocusTraversalKeysEnabled(false);
        exchangeRate.setFocusable(false);

        rateLabel.setText("Exchange Rate:");

        amountNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        amountNameLabel.setText("jLabel1");

        convertedAmountNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        convertedAmountNameLabel.setText("jLabel2");

        enterAmountLabel.setLabelFor(amount);
        enterAmountLabel.setText("Enter Amount:");

        jLabel1.setLabelFor(convertedAmount);
        jLabel1.setText("Converted Amount:");

        jLabel2.setFont(new java.awt.Font("Courier", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Currency Converter");

        amount.setToolTipText("Enter Amount");

        fileMenu.setText("File");

        updateMenuItem.setText("Update");
        updateMenuItem.setToolTipText("");
        fileMenu.add(updateMenuItem);

        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        aboutMenu.setText("About");

        aboutMenuItem.setText("About...");
        aboutMenuItem.setToolTipText("");
        aboutMenu.add(aboutMenuItem);

        menuBar.add(aboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterAmountLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(convertedAmountNameLabel)
                    .addComponent(amountNameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amount, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(convertedAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromCurrencyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toCurrencyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(amountNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromCurrencyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterAmountLabel)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(convertedAmountNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toCurrencyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(convertedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exchangeRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateLabel))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        updateLabels();
        amount.setValue(1.05);
        NumberFormat numFormat = NumberFormat.getNumberInstance();
        numFormat.setMinimumFractionDigits(2);
        NumberFormatter numFormatter = new NumberFormatter(numFormat);
        DefaultFormatterFactory numFactory = new DefaultFormatterFactory(numFormatter);
        amount.setFormatterFactory(numFactory);
        convertedAmount.setFormatterFactory(numFactory);
    }//GEN-LAST:event_formWindowOpened

    private void fromCurrencyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCurrencyListActionPerformed
        // TODO add your handling code here:
        updateLabels();
        //setFromNumberFormat(currencies[fromCurrencyList.getSelectedIndex()]);
    }//GEN-LAST:event_fromCurrencyListActionPerformed

    private void toCurrencyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCurrencyListActionPerformed
        // TODO add your handling code here:
        updateLabels();
        //setToNumberFormat(currencies[toCurrencyList.getSelectedIndex()]);
    }//GEN-LAST:event_toCurrencyListActionPerformed

    private void updateLabels() {
        amountNameLabel.setText(countries[fromCurrencyList.getSelectedIndex()]);
        convertedAmountNameLabel.setText(countries[toCurrencyList.getSelectedIndex()]);
        
        exchangeRate.setText(null);
    }
    
//    public void setFromNumberFormat(String unit) {
//        Locale locale = new Locale(unit);
//        NumberFormat numFormat = NumberFormat.getNumberInstance();
//        numFormat.setMinimumFractionDigits(2);
//        NumberFormatter numFormatter = new NumberFormatter(numFormat);
//        DefaultFormatterFactory numFactory = new DefaultFormatterFactory(numFormatter);
//        amount.setFormatterFactory(numFactory);
//    }
//    
//    public void setToNumberFormat(String unit) {
//        Locale locale = new Locale(unit);
//        Locale.setDefault(locale);
//        NumberFormat numFormat = NumberFormat.getCurrencyInstance(locale);
//        NumberFormatter numFormatter = new NumberFormatter(numFormat);
//        numFactory = new DefaultFormatterFactory(numFormatter);
//        convertedAmount.setFormatterFactory(numFactory);
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConverterWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConverterWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JFormattedTextField amount;
    private javax.swing.JLabel amountNameLabel;
    private javax.swing.JFormattedTextField convertedAmount;
    private javax.swing.JLabel convertedAmountNameLabel;
    private javax.swing.JLabel enterAmountLabel;
    private javax.swing.JTextField exchangeRate;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox fromCurrencyList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JComboBox toCurrencyList;
    private javax.swing.JMenuItem updateMenuItem;
    // End of variables declaration//GEN-END:variables
}
